### ISSUE TITLE
How can I get the data in my web application(nodejs)

### ISSUE THREAD

**Issue by mylordl** [itssimple/overwolf-get-supported-features#3]
I am using the web api with node js and I read the documentation that exists of the API, but it is not clear to me how to use the events to obtain the data of a custom live fortnite game from the web

![image](https://user-images.githubusercontent.com/74635135/99473843-6b891800-2919-11eb-8856-3eb88d271325.png)

I start the Fortnite game and through which method do I get the information via nodejs? or how is the process?

thx so much!

**Comment by itssimple** [comment]
Hey!

To be able to use this properly, you'd need to use the package through an [Overwolf application](https://overwolf.github.io/docs/start/getting-started).

Because, by itself, it is just a way to tell what features are supported, but if you use this from within an Overwolf application, you can build all sorts of apps!

You can find the [currently available apps for Overwolf here](https://www.overwolf.com/browse-by-game/fortnite)! :)

So you can't use it through the web only, you need to install Overwolf with one of the above apps for it to work, or write your own.
